### ISSUE TITLE
gearshifft command line app

### ISSUE THREAD

**Issue by psteinb** [mpicbg-scicomp/gearshifft#8]
[disclaimer: this is a brain storming issue]

I could imagine gearshifft to yield a command line app that behaves like:

```
#runs all tests (complex, real) with all supported FFT libraries and all predefined shapes
$ gearshifft race  

#runs all tests with all supported FFT libraries with 64-bit doubles and all predefined shapes
$ gearshifft race -fp64 
```

one could imagine a specific verb to run with a specific library only:

```
$ gearshifft clfft -fp64
```

additional shapes could be handed over in terms of more arguments:

```
$ gearshifft race 1024 1024x32 1024x32x64
```

(a simple flag could indicate that these additional shapes are to be added to the default ones or if they should be performed exclusively)

**Comment by tdd11235813** [comment]
Well, I am not really satisfied with the current solution either. On the one hand I guess, a test suite normally should not contain flags. On the other hand users want to test their own shapes.
And I "abuse" the test suite more as an experiment suite framework ;)
Suggestions:
- I'd like to leave the lib implementations to separated binaries due to linkage issues.
- A "gearshifft_clfft", ... now would take precision as an command-line argument.
- shapes are stored row-wise in a text file
  - Call: `gearshifft_clfft [-fp64] [my_shapes.txt] [my_output.csv]`

Command line "parsing" is already built in as of the verbosity feature, and a call actually looks like:
`gearshifft -- [-v] [-fp64]  ...`
Without the '--' boost is jumping in with its own command-line flags for testing.

**Comment by tdd11235813** [comment]
I would close this now as #16 provides the wanted implementation.
